config/routes.rb
Rails.application.routes.draw do
  get 'promote_activities/index'
  get 'pages/index'
  get 'user_page/:user_id', to: 'pages#user_page', as: 'user_page'
  get 'user_calendar/:user_id', to: 'pages#user_calendar', as: 'user_calendar'
  
  post 'activity/:user_id', to: 'user_activities#create', as: 'asigne_activity'
  get 'edit_user_act/:user_id/:activity_id', to: 'user_activities#edit', as: 'edit_user_activity'
  delete 'activity/:user_id/:activity_id', to: 'user_activities#destroy', as: 'destroy_activity'
  patch 'edit/:user_id/:activity_id', to: 'user_activities#update', as: 'update_user_activity'
  patch 'edit_calendar/:activity_id', to: 'user_activities#update_calendar', as: 'update_user_calendar'

  get 'activities/new'
  post 'new_activity', to: 'activities#create', as: 'new_activity'
  get 'activity/:id', to: 'activities#index', as: 'activity'
  get 'edit_activity/:activity_id', to: 'activities#edit', as: 'edit_activity'
  patch 'update_activity/:activity_id', to: 'activities#update', as: 'update_activity'
  
  get 'promote_activities/:user_id', to: 'promote_activities#index', as: 'promote_activities'
  get 'new_promote', to: 'promote_activities#new', as: 'new_promote'
  post 'create_promote/:user_id', to: 'promote_activities#create', as: 'create_promote'
  delete 'promote/:id', to: 'promote_activities#destroy', as: 'destroy_promote'

  post 'contacts/:id', to: 'contacts#create', as: 'contacts'
  delete 'contacts/:id', to: 'contacts#destroy', as: 'destroy_contacts'

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_activity.html.erb
  <% @activities.each do |activity| %>
  <ul class="resultado_fila">
  	<li><%= link_to activity.name, activity_path(activity.id) %></li>
  </ul>
  <% end %>

     

app/views/pages/index.html.erb
<% if user_signed_in? %>
	<%= form_with model: @activity, url: asigne_activity_path(current_user), method: :post, local: true do |f| %>

		<%= f.label :registrar_actividad %>
		<%= f.collection_select :activity_id, @user_activities, :id, :name, :prompt => true %>

		<%= f.submit "Enviar" %>

	<% end %>

	<%= link_to 'Crear actividad nueva', activities_new_path %><br>

<% end %>
<br>
<form>
	<input name="q" placeholder="Buscar...">
</form>
<div id="resultado">
	<%= render 'activity' %>
</div>
<hr>


<% @sucesos.each do |evento|%>
	<div class="evento col-5 row">
		
		<div class="">
			<img src="<%= evento.user.photo.thumb %>" class="foto-index">
		</div>
		<div class="col-9">
			<p class="texto-index"><%= link_to evento.user.name, user_page_path(evento.user_id) %> <%= evento.activity.category.past %>
			<%= link_to evento.activity.name, activity_path(evento.activity_id) %><br>
			Categoría: <%= evento.activity.category.sustantivo %></p>
		</div>
		<div>
			<img src="<%= evento.activity.photo.normal %>">
			<% evento.actuser_photo.each do |pho| %>
				<img src="<%= pho.photo %>">
			<% end %>
			<br>
			<p><%= time_ago_in_words(evento.created_at) %></p>
		</div>
	</div>
<% end %>


<br>
<hr>
<h5>Conectados</h5>
<% if user_signed_in? %>
	<% @contacts.each do |contact| %>
		<%= link_to User.find(contact.followed_id).name, user_page_path(User.find(contact.followed_id)) %><br>
	<% end %>
<% end %>

<br><br>
<hr>
<h5>Total Usuarios</h5>
<% @users.each do |user| %>
	<%= link_to user.name, user_page_path(user) %> <img src="<%= user.photo.thumb %>" >

	<br>
<% end %>
<hr>

<h5>Publicidad</h5>

<% @promotes.each do |promote| %>
	<%= promote.activity.name %><br>
<% end %>


<script>
  $("[name=q]").keyup(function(event){
    if($(this).val().length > 2 || $(this).val().length == 0){
      $.ajax({
        url: '<%= pages_index_path %>',
        type: 'GET',
        dataType: 'script',
        data: {q: $(this).val()
      }

    })}
  })
</script>

app/views/pages/index.js.erb
$("#resultado").html("<%= j render 'activity' %>")

app/views/pages/user_calendar.html.erb
<div class= col-4">
	<img src="<%= @user.photo.thumb %>" class="foto_usuario"> 
	<h2><%= @user.name %></h2>
</div>
<br>
<div id="calendar">
</div>

<script>
	$("#calendar").fullCalendar({
		events: '<%= user_calendar_path %>',
		
		eventDrop: function( event, delta, revertFunc, jsEvent, ui, view) {
			$.ajax({
				url: '/edit_calendar/' + event.id,
				type: 'PATCH',
				dataType: 'json',
				data: {
					user_activity: {start: event.start.format(), },
					authenticity_token: "<%= form_authenticity_token %>"
				}
			})
		},

		editable: true,
		displayEventTime: false,
	})
</script>

app/views/pages/user_page.html.erb
<div class="titulo-user col-5">
	<img src="<%= @user.photo.normal %>" class="foto_usuario"> 
	<h2><%= @user.name %></h2>
</div>
<br>

<% if user_signed_in? && @following %>
	<%=link_to "Dejar de seguir a #{@user.name}", destroy_contacts_path(@user.id), method: :delete, :class => 'btn btn-info' %>
<% elsif user_signed_in? && @user.id != current_user.id %>
	<%=link_to "Seguir a #{@user.name}", contacts_path(@user.id), method: :post, :class => 'btn btn-info' %>
<% end %>

<br><br>
<hr>
<div class="row">
	<div class="col-6">
		<h3>Actividades Realizadas</h3>
		<% @categories.each do |category| %>
			<% @act_user_realizadas.each do |useract| %>
				<% if useract.activity.category_id == category.id %>
					<h5><%= category.sustantivo %> que <%= category.past %></h5>
					<% @act_user_realizadas.each do |act| %>
						<% if act.activity.category_id == category.id %>
							<% if act.activity.author %>
								<img src="<%= act.activity.photo.thumb %>" >
								<%= link_to act.activity.name, activity_path(act.activity.id) %> de <%= act.activity.author %> | <%= category.participio %> el <%= act.start.strftime("%F") %> | registrado <%= time_ago_in_words(act.activity.created_at) %> ago 
								<% act.actuser_photo.each do |picture| %>
									<img src="<%= picture.photo.thumb %>" > 
								<% end %><br>
								
								<% if can?(:destroy, act) %>
									<%= link_to 'Editar', edit_user_activity_path(@user,act.activity.id) %>
									<%= link_to 'Borrar actividad', destroy_activity_path(@user,act.activity.id), method: :delete %>
								<% end %>
							<% else %>
								<img src="<%= act.activity.photo.thumb %>" >
								<%= link_to act.activity.name, activity_path(act.activity.id) %> | <%= category.participio %> el <%= act.start.strftime("%F") %> | registrado <%= time_ago_in_words(act.activity.created_at) %> ago
								<% if can?(:destroy, act) %>
									<%= link_to 'Editar', edit_user_activity_path(@user,act.activity.id) %>
									<%= link_to 'Borrar actividad', destroy_activity_path(@user,act.activity.id), method: :delete %>
								<% end %>
							<% end %>
							
							<br>
						<% end %>
					<% end %><br>
					<% break %>
				<% end %>
			<% end %>
		<% end %>
	</div>
	<div class="col-6">
		<% if @act_user_por_realizar != [] %>
			<h3>Actividades por Realizar <%= link_to "Ver en Calendario", user_calendar_path(@user.id), :class=> 'btn btn-sm btn-dark float-right', :style=> 'width:180px;' %></h3> 
		<% end %>
		<% @categories.each do |category| %>
			<% @act_user_por_realizar.each do |useract| %>
				<% if useract.activity.category_id == category.id %>
					<h5><%= category.sustantivo %> que <%= category.futuro %></h5>
					<% @act_user_por_realizar.each do |act| %>
						<% if act.activity.category_id == category.id %>
							<% if act.activity.author %>
								<img src="<%= act.activity.photo.thumb %>" >
								<%= link_to act.activity.name, activity_path(act.activity.id) %> de <%= act.activity.author %> | planificada para el <%= act.start.strftime("%F") %> | registrado <%= time_ago_in_words(act.activity.created_at) %> ago 
								<% act.actuser_photo.each do |picture| %>
									<img src="<%= picture.photo.thumb %>" > 
								<% end %><br>
								
								<% if can?(:destroy, act) %>
									<%= link_to 'Editar', edit_user_activity_path(@user,act.activity.id) %>
									<%= link_to 'Borrar actividad', destroy_activity_path(@user,act.activity.id), method: :delete %>
								<% end %>
							<% else %>
								<img src="<%= act.activity.photo.thumb %>" >
								<%= link_to act.activity.name, activity_path(act.activity.id) %> | <%= category.participio %> el <%= act.start.strftime("%F") %> | registrado <%= time_ago_in_words(act.activity.created_at) %> ago
								<% if can?(:destroy, act) %>
									<%= link_to 'Editar', edit_user_activity_path(@user,act.activity.id) %>
									<%= link_to 'Borrar actividad', destroy_activity_path(@user,act.activity.id), method: :delete %>
								<% end %>
							<% end %>
							
							<br>
						<% end %>
					<% end %><br>
					<% break %>
				<% end %>
			<% end %>
		<% end %>
	</div>
</div>

		