config/routes.rb
Rails.application.routes.draw do
  get 'promote_activities/index'
  get 'pages/index'
  get 'user_page/:user_id', to: 'pages#user_page', as: 'user_page'
  get 'user_calendar/:user_id', to: 'pages#user_calendar', as: 'user_calendar'
  
  post 'activity/:user_id', to: 'user_activities#create', as: 'asigne_activity'
  get 'edit_user_act/:user_id/:activity_id', to: 'user_activities#edit', as: 'edit_user_activity'
  delete 'activity/:user_id/:activity_id', to: 'user_activities#destroy', as: 'destroy_activity'
  patch 'edit/:user_id/:activity_id', to: 'user_activities#update', as: 'update_user_activity'
  patch 'edit_calendar/:activity_id', to: 'user_activities#update_calendar', as: 'update_user_calendar'

  get 'activities/new'
  post 'new_activity', to: 'activities#create', as: 'new_activity'
  get 'activity/:id', to: 'activities#index', as: 'activity'
  get 'edit_activity/:activity_id', to: 'activities#edit', as: 'edit_activity'
  patch 'update_activity/:activity_id', to: 'activities#update', as: 'update_activity'
  
  get 'promote_activities/:user_id', to: 'promote_activities#index', as: 'promote_activities'
  get 'new_promote', to: 'promote_activities#new', as: 'new_promote'
  post 'create_promote/:user_id', to: 'promote_activities#create', as: 'create_promote'
  delete 'promote/:id', to: 'promote_activities#destroy', as: 'destroy_promote'

  post 'contacts/:id', to: 'contacts#create', as: 'contacts'
  delete 'contacts/:id', to: 'contacts#destroy', as: 'destroy_contacts'

  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
	has_many :user_activity, dependent: :destroy
	has_many :users, through: :user_activity, dependent: :destroy

	belongs_to :category, optional: true
	has_many :promote_activity, dependent: :destroy

	belongs_to :user, class_name: 'User', foreign_key: :owner_id

	mount_uploader :photo, ImageUploader
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	authorize_resource

	def index
		@activity = Activity.find(params[:id])
		if user_signed_in?
			if UserActivity.where(user_id: current_user.id,activity_id: @activity.id) != []
				@registrada = true
			else
				@registrada = false
			end
		end
	end

	def new
		@activity = Activity.new
		@categories = Category.all
	end

	def create
		@activity = Activity.new
		@activity.name = params[:activity][:name]
		@activity.category_id = params[:activity][:category_id]
		@activity.photo = params[:activity][:photo]
		@activity.remote_photo_url = params[:activity][:remote_photo_url]
		@activity.owner_id = current_user.id
		@activity.save
		redirect_to root_path, notice: 'la actividad fue creada. Puede ingresarla a su registro si lo desea'
	end

	def edit	
		@activity = Activity.where(id: params[:activity_id]).first
		@categories = Category.all
	end

	def update
		@activity = Activity.where(id: params[:activity_id]).first
		@activity.update(author: params[:activity][:author])
		@activity.update(category_id: params[:activity][:category_id])
		@activity.update(photo: params[:activity][:photo])
		@activity.update(remote_photo_url: params[:activity][:remote_photo_url])
    	redirect_to user_page_path(current_user)
	end

	
	
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/edit.html.erb
<h2>Editar Actividad </h2>
<br>
<% if user_signed_in? %>
	<%= form_with model: Activity, url: update_activity_path(@activity), method: :patch, local: true do |f| %>
		
		<%= f.label :author %>
		<%= f.text_field :author %>	<br>

		<%= f.label :category %>
		<%= f.collection_select :category_id, @categories, :id, :name, :prompt => true %> <br>


	    <%= f.label :photo %> <br>
	    <%= f.file_field :photo %>
	    <%= f.text_field :remote_photo_url %><br>

			

		<%= f.submit "Enviar" %>

	<% end %>
<% end %>

app/views/activities/edit2.html.erb
<h2>Editar actividad <%= @activity.activity.name %> de <%= @user.name %></h2>


<% if user_signed_in? && can?(:update, @activity) %>
	<%= form_with model: UserActivity, url: update_activity_path(@user), method: :patch, local: true do |f| %>

		<%= f.label :start %>
		<%= f.text_field :start %>		

		<%= f.submit "Enviar" %>

	<% end %>
<% end %>

<br><br>

app/views/activities/index.html.erb
<div id="fondo-act" class="fondo_activity">

	<div class="cuadro_centro_act">
		<div class="row">
			<div class="col-6">
				<h3><%= @activity.name %></h3><br>
				<img src="<%= @activity.photo.normal %>">
			</div>
			<div class="col-6 boton">
				<% if user_signed_in? %>
					<% if @registrada %>
					<%= link_to 'Borrar registro de actividad', destroy_activity_path(current_user, :activity_id=> @activity.id), method: :delete, :class => 'btn btn-danger' %>
					<% else %>
						<%= link_to 'Registrar actividad', asigne_activity_path(current_user, :activity_id=> @activity.id, :status=> 'realizada'), method: :post, :class => 'btn btn-danger' %>
						<%= link_to 'Marcar como por realizar', asigne_activity_path(current_user, :activity_id=> @activity.id, :status=> 'por_hacer'), method: :post, :class => 'btn btn-warning' %>
					<% end %>
				<% end %>
			</div>
			<br>

		</div>
		<br>
		<% if can?(:edit, @activity) %>
			<%= link_to 'Editar actividad', edit_activity_path(@activity.id), :class => 'btn btn-info' %>
		<% end %>

		<img src="<%= @activity.photo %>" id="lo" style="display: none">
	</div>
</div>

<script>
		
		$("#fondo-act").backstretch(document.getElementById("lo").src)
		
		

</script>

app/views/activities/new.html.erb
<h2>Crear nueva actividad </h2>
<br>

<% if user_signed_in? %>
	<%= form_with model: @activity, url: new_activity_path, method: :post, local: true do |f| %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>	<br>

		<%= f.label :autor %>
		<%= f.text_field :author %>	<br>

		<%= f.label :categoría %>
		<%= f.collection_select :category_id, @categories, :id, :name, :prompt => true %><br>


	    <%= f.label :photo %> <br>
	    <%= f.file_field :photo %>
	    <%= f.text_field :remote_photo_url %><br>

			

		<%= f.submit "Enviar" %>

	<% end %>
<% end %>